Add Cryptography to Reqs
The reqs were missing a package, see below

```
(.venv) ➜  src git:(training) ✗ python dpe.py

('xbar_ip_energy_dict', {'60': 170.00000000000003, '0': 170.00000000000003, '20': 170.00000000000003, '70': 170.00000000000003, '90': 170.00000000000003, '80': 170.00000000000003, '30': 170.00000000000003, '50': 170.00000000000003, '40': 170.00000000000003, '10': 170.00000000000003})
('xbar_ip_energy_dict', {'60': 170.00000000000003, '0': 170.00000000000003, '20': 170.00000000000003, '70': 170.00000000000003, '90': 170.00000000000003, '80': 170.00000000000003, '30': 170.00000000000003, '50': 170.00000000000003, '40': 170.00000000000003, '10': 170.00000000000003})
Traceback (most recent call last):
  File "dpe.py", line 62, in <module>
    from Factory import Factory
  File "/home/ubuntu22/git-repos/2puma/puma-simulator/Security/Factory.py", line 12, in <module>
    from PumaFernet import PumaFernet
  File "/home/ubuntu22/git-repos/2puma/puma-simulator/Security/PumaFernet.py", line 13, in <module>
    from cryptography.fernet import Fernet
ImportError: No module named cryptography.fernet
```